'use client';
import {useState,useEffect, useCallback} from 'react';
import {ArrowUpRight,Search,Sparkles,Film,MessageCircle,Ticket,Plus,Check,ArrowRight,Send,Star,Bookmark,LoaderCircle} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {movies, type Movie} from '@/lib/movies';
type Social={user:{id:string;name:string}|null;reviews:any[];people:any[];saved:Movie[];messages:any[]};
const initial:Social={user:null,reviews:[],people:[],saved:[],messages:[]};
const verdictLabel:Record<string,string>={theatre:'Theatre-worthy',home:'Better at home',either:'Either screen'};
export default function Home(){
const [tab,setTab]=useState('discover'),[query,setQuery]=useState(''),[genre,setGenre]=useState('All films'),[catalog,setCatalog]=useState(movies),[mode,setMode]=useState('curated'),[page,setPage]=useState(1),[pages,setPages]=useState(1),[loading,setLoading]=useState(false),[social,setSocial]=useState<Social>(initial),[notice,setNotice]=useState(''),[selected,setSelected]=useState<Movie|null>(null),[dialog,setDialog]=useState(''),[body,setBody]=useState(''),[rating,setRating]=useState(4),[verdict,setVerdict]=useState('theatre'),[busy,setBusy]=useState(false),[person,setPerson]=useState(''),[name,setName]=useState(''),[chat,setChat]=useState<{role:string;content:string}[]>([]),[prompt,setPrompt]=useState('');
const refresh=useCallback(async()=>{try{const r=await fetch('/api/social');const d:any=await r.json();if(r.ok)setSocial(d);else setNotice(d.error);}catch{setNotice('Could not load the film club. Please try again.')}},[]);
useEffect(()=>{refresh()},[refresh]);
useEffect(()=>{const ac=new AbortController();const timer=setTimeout(async()=>{setLoading(true);try{const r=await fetch(`/api/catalog?q=${encodeURIComponent(query)}&page=${page}`,{signal:ac.signal});const d:any=await r.json();if(!r.ok)throw Error(d.error);setCatalog(d.movies);setMode(d.mode);setPages(d.pages);}catch(e){if(!ac.signal.aborted)setNotice((e as Error).message)}finally{if(!ac.signal.aborted)setLoading(false)}},250);return()=>{clearTimeout(timer);ac.abort()}},[query,page]);
useEffect(()=>{if(tab!=='messages')return;const timer=setInterval(refresh,12000);return()=>clearInterval(timer)},[tab,refresh]);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const ac=new AbortController();Promise.resolve(context.registerTool({name:'search_movies',description:'Search the movie catalog and show results on the discovery shelf.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(typeof input?.query!=='string'||input.query.length>200)throw Error('Query must be a string of at most 200 characters.');const r=await fetch(`/api/catalog?q=${encodeURIComponent(input.query)}`);const d:any=await r.json();if(!r.ok)throw Error(d.error);setQuery(input.query);setPage(1);setTab('discover');setCatalog(d.movies);return {mode:d.mode,movies:d.movies.map((m:Movie)=>({id:m.id,title:m.title,year:m.year}))}}},{signal:ac.signal})).catch(()=>{});return()=>ac.abort()},[]);
async function mutate(data:any){setBusy(true);try{const r=await fetch('/api/social',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d:any=await r.json();if(!r.ok)throw Error(d.error);await refresh();return true}catch(e){setNotice((e as Error).message);return false}finally{setBusy(false)}}
async function save(m:Movie){if(await mutate({action:'save',movie:m,remove:social.saved.some(x=>x.id===m.id)}))setNotice(social.saved.some(x=>x.id===m.id)?'Removed from your watchlist.':'Added to your watchlist.')}
function detail(m:Movie){setSelected(m);setDialog('movie');setBody('')}
function sendMovie(m:Movie){setSelected(m);setDialog('send');setBody(`I think you’d like ${m.title}. `)}
async function ask(text:string){if(!text.trim()||busy)return;setNotice('');const next=[...chat,{role:'user',content:text.trim()}].slice(-18);setChat(next);setPrompt('');setBusy(true);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setChat([...next,{role:'assistant',content:d.text}])}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
const visible=(tab==='watchlist'?social.saved:catalog).filter(m=>genre==='All films'||m.genre===genre);const selectedReviews=social.reviews.filter(r=>r.movie_id===selected?.id);const people=social.people.filter(p=>p.id!==social.user?.id);const thread=social.messages.filter(m=>(m.sender===person&&m.recipient===social.user?.id)||(m.recipient===person&&m.sender===social.user?.id)).slice().reverse();
function card(m:Movie){const saved=social.saved.some(x=>x.id===m.id),reviews=social.reviews.filter(r=>r.movie_id===m.id);return <article className="movie-card" key={m.id}><button className="poster-button" onClick={()=>detail(m)} aria-label={`View ${m.title}`}><img src={m.poster||undefined} alt={`${m.title} poster`} loading="lazy" onError={e=>{e.currentTarget.style.display='none'}}/><div className="poster-fallback">{m.title}</div><span className="poster-overlay">Open film <ArrowUpRight size={20}/></span></button><button className={`save-button ${saved?'saved':''}`} aria-label={`${saved?'Remove':'Save'} ${m.title}`} disabled={busy} onClick={()=>save(m)}>{saved?<Check size={18}/>:<Plus size={18}/>}</button><button className="movie-title" onClick={()=>detail(m)}>{m.title}</button><div className="movie-meta"><span>{m.year} · {m.genre}</span>{reviews.length>0&&<span className="score"><Star size={12}/>{(reviews.reduce((a,r)=>a+r.rating,0)/reviews.length).toFixed(1)}</span>}</div></article>}
return <main><header className="topbar"><a className="brand" href="/">afterframe<span>✳</span></a><nav aria-label="Main navigation"><button className={tab==='discover'?'active':''} onClick={()=>setTab('discover')}>Discover</button><button className={tab==='community'?'active':''} onClick={()=>setTab('community')}>Community</button><button className={tab==='watchlist'?'active':''} onClick={()=>{setTab('watchlist');setGenre('All films')}}>My watchlist</button></nav><button className={`icon ${tab==='messages'?'active':''}`} aria-label="Open messages" onClick={()=>setTab('messages')}><MessageCircle size={21}/></button><button className="avatar" aria-label="Your profile" onClick={()=>setDialog('profile')}>{social.user?.name?.slice(0,1)||'＋'}</button></header><div className="page">
{notice&&<div className="notice" role="status"><span>{notice}</span><button aria-label="Dismiss notification" onClick={()=>setNotice('')}>×</button></div>}
{tab==='discover'&&<><div className="eyebrow">GOOD FILMS. BETTER CONVERSATIONS.</div><div className="intro"><h1>Stay for the<br/><em>afterthought.</em></h1><div className="intro-right"><p>Your next favourite film is out there.<br/>Find it through people, not just ratings.</p><label className="search"><Search size={20}/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Search for a film…" aria-label="Search movies"/><span>{loading?<LoaderCircle size={16}/>: '↵'}</span></label></div></div>{!query&&<div className="feature-grid"><article className="feature"><img className="feature-image" src={movies[0].poster} alt="Dune Part Two theatrical poster"/><div className="feature-shade"/><div className="feature-content"><div className="eyebrow">THE BIG-SCREEN QUESTION <span>01 / 08</span></div><div className="feature-bottom"><span className="ticket-label"><Ticket size={15}/> YOUR SCREEN. YOUR VERDICT.</span><h2>Dune: Part Two</h2><p>Sand. Scale. Sound.<br/>Would you pay for the biggest screen?</p><button className="lime" onClick={()=>detail(movies[0])}>Give your verdict <ArrowUpRight size={18}/></button></div></div></article><article className="bot-card"><div className="bot-top"><Sparkles/><span>THE PROJECTIONIST</span><span className="dot"/></div><h2>“Something that<br/>stays with me.”</h2><p>No endless scrolling. Tell our film companion<br/>what you’re in the mood for.</p><div className="mood-list">{['A beautiful heartbreak','Mind-bending','A comfort watch'].map(m=><button key={m} onClick={()=>{setPrompt(m);setDialog('chat')}}>{m} ↗</button>)}</div><button className="bot-cta" onClick={()=>setDialog('chat')}>Let’s find your film <ArrowUpRight size={20}/></button></article></div>}</>}
{(tab==='discover'||tab==='watchlist')&&<><div className="section-head"><h2>{tab==='watchlist'?'Saved for the right night':query?`Results for “${query}”`:'Worth talking about'} <span>↗</span></h2><span>{tab==='watchlist'?`${social.saved.length} FILMS`:mode==='curated'?'THE CURATED SHELF · 8 FILMS':'EXPLORE THE CATALOG'}</span></div><Tabs value={genre} onValueChange={v=>setGenre(String(v))}><TabsList className="genre-tabs" variant="line">{['All films','Sci-Fi','Thriller','Romance','Comedy','Drama','Musical'].map(g=><TabsTrigger key={g} value={g}>{g}</TabsTrigger>)}</TabsList></Tabs><div className="movie-grid">{visible.map(card)}</div>{!visible.length&&<div className="empty"><Bookmark/><div><h3>{tab==='watchlist'?'Make room for your next favourite.':'No films found.'}</h3><p>{tab==='watchlist'?'Tap + on a film to save it for later.':'Try another title or select All films. The curated catalog is available until live search is connected.'}</p></div></div>}{pages>1&&<div className="pager"><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} / {pages}</span><button disabled={page===pages} onClick={()=>setPage(page+1)}>Next</button></div>}{tab==='discover'&&<div className="shelf-foot"><span>{mode==='curated'?'A handpicked starting point. Full-catalog search is awaiting its movie-data connection.':'Movie data from TMDB. This product uses the TMDB API but is not endorsed or certified by TMDB.'}</span><button onClick={()=>setTab('community')}>Find your film people <ArrowRight size={16}/></button></div>}</>}
{tab==='community'&&<><div className="eyebrow">THE CONVERSATION AFTER THE CREDITS</div><div className="view-heading"><h1>The film <em>club.</em></h1><button className="lime" onClick={()=>setDialog('profile')}>Join the conversation <Plus size={18}/></button></div><p>Recommendations from real people. Honest reviews. No spoilers without warning.</p><div className="community-grid"><section><div className="section-head"><h2>From the community</h2><span>{social.reviews.length} REVIEWS</span></div>{!social.reviews.length&&<div className="empty"><MessageCircle/><div><h3>The first word is yours.</h3><p>Choose a film and write the first review for this club.</p><button onClick={()=>setTab('discover')}>Find a film <ArrowUpRight size={17}/></button></div></div>}{social.reviews.map(r=>{const m=JSON.parse(r.movie);return <article className="review" key={r.id}><div className="review-top"><span className="avatar">{r.name[0]}</span><strong>{r.name}</strong><span>{new Date(r.created).toLocaleDateString()}</span></div><button className="review-film" onClick={()=>detail(m)}>{m.title} <ArrowUpRight size={15}/></button><div className="review-rating">{'★'.repeat(r.rating)} <span className="verdict">{verdictLabel[r.verdict]}</span></div><p>{r.body}</p><button onClick={()=>sendMovie(m)}>Pass this film on <Send size={14}/></button></article>})}</section><aside className="club-panel"><Ticket size={28}/><h2>A great film.<br/>But which screen?</h2><p>Rate the film, then give a separate verdict on the experience.</p><div>Theatre-worthy <span>↗</span></div><div>Better at home <span>⌂</span></div><div>Either screen <span>↔</span></div><h3>Your film people</h3>{people.length?people.map(p=><button key={p.id} onClick={()=>{setPerson(p.id);setTab('messages')}}>{p.name}<MessageCircle size={16}/></button>):<p>Members appear here when they join the club.</p>}</aside></div></>}
{tab==='messages'&&<><div className="eyebrow">SEND A FILM. START A CONVERSATION.</div><div className="view-heading"><h1>The <em>backroom.</em></h1><button onClick={refresh}>Refresh messages</button></div><div className="messenger"><aside><h3>Your film people</h3>{people.length?people.map(p=><button className={person===p.id?'person-active':''} key={p.id} onClick={()=>setPerson(p.id)}><span className="avatar">{p.name[0]}</span>{p.name}</button>):<p>No other members yet. Invite someone to the club once the site is shared.</p>}</aside><section>{person?<><h3>{people.find(p=>p.id===person)?.name}</h3><div className="thread">{thread.length?thread.map(m=><div className={`bubble ${m.sender===social.user?.id?'mine':''}`} key={m.id}><small>{m.sender_name}</small><p>{m.body}</p>{m.movie&&<button onClick={()=>detail(JSON.parse(m.movie))}><Film size={16}/>{JSON.parse(m.movie).title} ↗</button>}<small>{new Date(m.created).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></div>):<div className="empty">A good film is a good conversation starter.</div>}</div><form className="message-form" onSubmit={async e=>{e.preventDefault();if(await mutate({action:'message',recipient:person,body}))setBody('')}}><input aria-label="Message" value={body} maxLength={3000} onChange={e=>setBody(e.target.value)} placeholder="Got a film they need to see?"/><button className="lime" disabled={busy||!body.trim()} aria-label="Send message"><Send size={18}/></button></form></>:<div className="message-empty"><MessageCircle size={38}/><h2>“You have to watch this.”</h2><p>Pick a film person to send a private recommendation.</p></div>}</section></div></>}
</div><footer><a href="/">afterframe © 2026</a><span>THE FILM ENDS. THE CONVERSATION DOESN’T.</span><button onClick={()=>setDialog('about')}>About & credits ↗</button></footer>
<Dialog open={Boolean(dialog)} onOpenChange={open=>{if(!open)setDialog('')}}><DialogContent className={`film-dialog ${dialog==='chat'?'chat-dialog':''}`}><DialogTitle className="dialog-title">{dialog==='movie'?selected?.title:dialog==='chat'?'The Projectionist':dialog==='send'?'Pass a good film on':dialog==='profile'?'Your place in the film club':'About Afterframe'}</DialogTitle><DialogDescription>{dialog==='movie'?`${selected?.year} · ${selected?.genre}`:dialog==='chat'?'Your conversational film companion. No spoilers unless you ask.':dialog==='send'?`Recommend ${selected?.title} to someone in the club.`:dialog==='profile'?'Choose the name other film lovers will see.':'An independent space for films and the conversations they leave behind.'}</DialogDescription>
{dialog==='movie'&&selected&&<><p>{selected.overview}</p><div className="detail-actions"><button onClick={()=>save(selected)} disabled={busy}><Bookmark size={17}/>{social.saved.some(x=>x.id===selected.id)?'Saved':'Watchlist'}</button><button onClick={()=>sendMovie(selected)}><Send size={17}/>Recommend</button></div><form className="review-form" onSubmit={async e=>{e.preventDefault();if(await mutate({action:'review',movie:selected,body,rating,verdict})){setBody('');setNotice('Your review is in the club.')}}}><h3>What stayed with you?</h3><fieldset><legend>Your rating</legend><RadioGroup className="stars" value={rating} onValueChange={v=>setRating(Number(v))} aria-label="Your rating">{[1,2,3,4,5].map(n=><label key={n}><RadioGroupItem value={n} aria-label={`${n} stars`}/><span style={{color:n<=rating?'#d3f66b':'#707765'}}>★</span><span className="sr-only">{n} stars</span></label>)}</RadioGroup></fieldset><fieldset><legend>Worth the theatre ticket?</legend><RadioGroup className="verdict-options" value={verdict} onValueChange={v=>setVerdict(String(v))} aria-label="Theatre verdict">{Object.entries(verdictLabel).map(([value,label])=><label key={value}><RadioGroupItem value={value}/>{label}</label>)}</RadioGroup></fieldset><textarea required maxLength={3000} value={body} onChange={e=>setBody(e.target.value)} placeholder="The scene, the feeling, the reason to watch. Please mark any spoilers." aria-label="Your review"/><button className="lime" disabled={busy}>{busy?'Saving…':'Publish review'} <ArrowUpRight size={17}/></button></form><h3>{selectedReviews.length} community reviews</h3>{selectedReviews.map(r=><div className="mini-review" key={r.id}><strong>{r.name}</strong><span>{'★'.repeat(r.rating)} · {verdictLabel[r.verdict]}</span><p>{r.body}</p></div>)}</>}
{dialog==='send'&&<form className="stack" onSubmit={async e=>{e.preventDefault();if(await mutate({action:'message',recipient:person,body,movie:selected})){setDialog('');setTab('messages');setBody('');setNotice('Recommendation sent.')}}}><label>Send to<Select value={person||null} onValueChange={v=>setPerson(String(v||''))}><SelectTrigger aria-label="Choose a film person"><SelectValue placeholder="Choose a film person">{people.find(p=>p.id===person)?.name}</SelectValue></SelectTrigger><SelectContent>{people.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></label>{!people.length&&<p>No other members yet. Recommendations will be available when someone else joins.</p>}<textarea required maxLength={3000} value={body} onChange={e=>setBody(e.target.value)} aria-label="Recommendation message"/><button className="lime" disabled={busy||!person}>Send recommendation <Send size={17}/></button></form>}
{dialog==='chat'&&<><div className="chat-thread">{!chat.length&&<div className="chat-intro"><Sparkles size={32}/><h2>What kind of night is it?</h2><p>Tell me a film you loved, a mood, or something you’d like to feel.</p><small>Powered by Google Gemini. Your messages are sent to Google to generate replies.</small></div>}{chat.map((m,i)=><div key={i} className={`bubble ${m.role==='user'?'mine':''}`}><small>{m.role==='user'?'You':'The Projectionist'}</small><p>{m.content}</p></div>)}{busy&&<p role="status">Finding the right words…</p>}</div><form className="message-form" onSubmit={e=>{e.preventDefault();ask(prompt)}}><input value={prompt} maxLength={3000} onChange={e=>setPrompt(e.target.value)} placeholder="A slow Sunday. A little bittersweet…" aria-label="Chat message"/><button className="lime" aria-label="Send to Projectionist" disabled={busy||!prompt.trim()}><ArrowRight size={20}/></button></form></>}
{dialog==='profile'&&<>{social.user?<form className="stack" onSubmit={async e=>{e.preventDefault();if(await mutate({action:'join',name:name||social.user?.name})){setDialog('');setNotice('You’re part of the club.')}}}><label>Your public name<input value={name} onChange={e=>setName(e.target.value)} maxLength={60} placeholder={social.user.name}/></label><p>Your reviews are visible to the club. Messages are visible only to their participants.</p><button className="lime" disabled={busy}>Save profile</button><a href="/signout-with-chatgpt?return_to=/" target="_top">Sign out ↗</a></form>:<><p>Sign in to save your watchlist, write reviews, and exchange film recommendations.</p><a className="sign-in" href="/signin-with-chatgpt?return_to=/" target="_top">Sign in with ChatGPT <ArrowUpRight size={17}/></a></>}</>}
{dialog==='about'&&<div className="credits"><p>Afterframe is a film-discovery and conversation space. Browse the live TMDB catalog, with eight curated films available as a starting point. No community ratings or conversations are fabricated.</p><p>Movie search is powered by TMDB; the Projectionist uses Google Gemini. Theatre verdicts reflect personal experience, not current screenings.</p><p>Poster images belong to their respective rights holders.</p>{movies.map(m=><a key={m.id} href={m.source} target="_blank" rel="noreferrer">{m.title} — poster source ↗</a>)}</div>}
{notice&&<p className="dialog-notice" role="status">{notice}</p>}
</DialogContent></Dialog></main>
}
