export type Movie={id:number;title:string;year:number;genre:string;genres?:string[];poster:string;source?:string;overview:string};
export const movies:Movie[]=[
{id:693134,title:'Dune: Part Two',year:2024,genre:'Sci-Fi',poster:'https://www.cinefilos.it/wp-content/uploads/2023/05/dune-parte-due-poster.jpg',source:'https://www.cinefilos.it/cinema-news/2023/dune-parte-due-ecco-il-primo-poster-del-film-con-timothee-chalamet-571121',overview:'Paul Atreides joins the Fremen on Arrakis, facing a choice between love and the fate of the universe.'},
{id:157336,title:'Interstellar',year:2014,genre:'Sci-Fi',poster:'https://images.flickdirect.com/movies/interstellar/interstellar-poster.jpg',source:'https://flickdirect.com/movie-review/1258/interstellar/movie.ashx',overview:'A pilot and a team of explorers travel beyond our galaxy in search of a future for humanity.'},
{id:496243,title:'Parasite',year:2019,genre:'Thriller',poster:'https://www.sagaftra.org/sites/default/files/styles/sa_staff_desktop_2x/public/staff_images/parasite.jpg?itok=j4kB61iU',source:'https://www.sagaftra.org/parasite',overview:'Two families on opposite sides of the economic divide become entangled in a darkly funny, unpredictable thriller.'},
{id:666277,title:'Past Lives',year:2023,genre:'Romance',poster:'https://cdn.mos.cms.futurecdn.net/AzD4z3vPgyt3rXwmXgrxjJ.jpg',source:'https://www.creativebloq.com/features/the-best-romance-film-posters-of-all-time',overview:'Childhood friends reconnect across continents and years, reflecting on the lives they chose and the ones they left behind.'},
{id:120467,title:'The Grand Budapest Hotel',year:2014,genre:'Comedy',poster:'https://es.web.img3.acsta.net/pictures/14/01/20/12/06/239820.jpg',source:'https://www.sensacine.com/peliculas/pelicula-207825/fotos/detalle/?cmediafile=9001705778',overview:'A devoted hotel concierge and his young protégé become caught up in a stolen painting, a family fortune, and a changing Europe.'},
{id:313369,title:'La La Land',year:2016,genre:'Musical',poster:'https://m.media-amazon.com/images/M/MV5BYmNkMjExZTUtMGIzOC00NTJkLWIzMmMtYTY5ZGZjOGJlZjBiXkEyXkFqcGc%40._V1_FMjpg_UX1000_.jpg',source:'https://www.imdb.com/title/tt3783958/mediaviewer/rm2129266432/',overview:'An aspiring actor and a jazz pianist fall in love while pursuing their dreams in Los Angeles.'},
{id:244786,title:'Whiplash',year:2014,genre:'Drama',poster:'https://m.media-amazon.com/images/M/MV5BMzVjZDI3N2YtYTU2Yi00ZWZjLTgwMmMtMzY1YjcyM2U2NDE4XkEyXkFqcGc%40._V1_FMjpg_UX1000_.jpg',source:'https://www.imdb.com/fr/title/tt2582802/mediaviewer/rm803995904/',overview:'A young jazz drummer pushes himself to extremes under a demanding instructor.'},
{id:545611,title:'Everything Everywhere All at Once',year:2022,genre:'Sci-Fi',poster:'https://es.web.img3.acsta.net/r_1280_720/pictures/22/03/01/10/45/0114540.jpg',source:'https://www.sensacine.com/peliculas/pelicula-270743/fotos/detalle/?cmediafile=21898282',overview:'A laundromat owner is pulled into a multiverse adventure that brings her family relationships into focus.'}
];
