import {cookies} from 'next/headers';
import {secret} from './server';
export type Session={token:string;user:{id:string;email?:string;user_metadata?:{username?:string}}};
const accessCookie='afterframe_access',refreshCookie='afterframe_refresh';
export function supabaseConfig(){const url=secret('SUPABASE_URL'),key=secret('SUPABASE_PUBLISHABLE_KEY');if(!url||!key||key.startsWith('sb_secret_'))throw new Error('Supabase is not configured.');return {url,key};}
export async function authRequest(path:string,body?:unknown,token?:string){const {url,key}=supabaseConfig();return fetch(`${url}/auth/v1/${path}`,{method:body?'POST':'GET',headers:{apikey:key,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});}
export async function setSession(value:{access_token:string;refresh_token:string;expires_in:number}){const jar=await cookies();const options={httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax' as const,path:'/'};jar.set(accessCookie,value.access_token,{...options,maxAge:Math.max(60,value.expires_in)});jar.set(refreshCookie,value.refresh_token,{...options,maxAge:60*60*24*30});}
export async function clearSession(){const jar=await cookies();jar.delete(accessCookie);jar.delete(refreshCookie);}
export async function getSession():Promise<Session|null>{const jar=await cookies(),token=jar.get(accessCookie)?.value; if(token){const response=await authRequest('user',undefined,token);if(response.ok)return {token,user:await response.json() as Session['user']};if(response.status>=500)throw new Error('Sign-in service is temporarily unavailable.');}
const refresh=jar.get(refreshCookie)?.value;if(!refresh)return null;const result=await authRequest('token?grant_type=refresh_token',{refresh_token:refresh});if(!result.ok){if(result.status>=500)throw new Error('Sign-in service is temporarily unavailable.');return null;}const data=await result.json() as any;await setSession(data);return {token:data.access_token,user:data.user};}
export async function userData(session:Session,path:string,options:{method?:string;body?:unknown;prefer?:string}={}):Promise<any>{if(!session.token)throw new Error('Sign in first.');const {url,key}=supabaseConfig();const response=await fetch(`${url}/rest/v1/${path}`,{method:options.method||'GET',headers:{apikey:key,Authorization:`Bearer ${session.token}`,'Content-Type':'application/json',...(options.prefer?{Prefer:options.prefer}:{})},body:options.body===undefined?undefined:JSON.stringify(options.body),signal:AbortSignal.timeout(15000)});if(!response.ok){const error=await response.json().catch(()=>({})) as any;if(['PGRST205','42P01','PGRST202'].includes(error.code))throw new Error('The Supabase tables still need to be set up.');if(response.status===403)throw new Error('You do not have permission for this club or record.');throw new Error('Could not save or load this item. Please check your input and try again.');}return response.status===204?null:response.json().catch(()=>null);}
