import {reviewInput} from '@/lib/review';
import {getSession,userData} from '@/lib/supabase';
import {failure} from '@/lib/server';
const empty={user:null,reviews:[],myReviews:[],people:[],saved:[],messages:[],recommendations:[],clubs:[],memberships:[]};
function movieOf(r:any){return {...r.movie,id:r.movie_id,title:r.movie_title,poster:r.poster_url||'',year:r.movie?.year||0,genre:r.movie?.genre||'Film',overview:r.movie?.overview||''};}
function reviewOf(r:any,names:Map<string,string>){return {...r,movie:JSON.stringify(movieOf(r)),name:names.get(r.user_id)||'Film lover',body:r.review_text,rating:r.rating||0,verdict:r.screen_verdict||(r.theatre_worthy===true?'theatre':r.theatre_worthy===false?'home':''),created:Date.parse(r.created_at)};}
export async function GET(){try{const session=await getSession();if(!session)return Response.json(empty,{headers:{'Cache-Control':'no-store'}});const uid=session.user.id;
const [profiles,reviews,clubs,memberships,saved,recommendations]=await Promise.all([
userData(session,'profiles?select=id,username,avatar_url'),userData(session,'reviews?select=*&order=created_at.desc'),userData(session,'clubs?select=*&order=created_at.desc'),userData(session,'memberships?select=club_id,user_id'),userData(session,`watchlist?select=movie&user_id=eq.${uid}`),userData(session,`recommendations?select=*&receiver_id=eq.${uid}&order=created_at.desc`)]);
const names=new Map<string,string>(profiles.map((p:any)=>[p.id,p.username]));const allReviews=reviews.map((r:any)=>reviewOf(r,names));return Response.json({user:{id:uid,name:names.get(uid)||'Film lover',email:session.user.email,avatar_url:profiles.find((p:any)=>p.id===uid)?.avatar_url},reviews:allReviews,myReviews:allReviews.filter((r:any)=>r.user_id===uid),people:profiles.map((p:any)=>({id:p.id,name:p.username,avatar_url:p.avatar_url})),clubs,memberships,saved:saved.map((r:any)=>r.movie),messages:[],recommendations:recommendations.map((r:any)=>({...r,movie:movieOf(r),sender_name:names.get(r.sender_id)||'Film lover'}))},{headers:{'Cache-Control':'no-store'}});
}catch(error){return failure(error,503)}}
export async function POST(request:Request){if(request.headers.get('origin')!==new URL(request.url).origin)return failure(new Error('Invalid request origin.'),403);try{const session=await getSession();if(!session)return failure(new Error('Sign in to save films and send recommendations.'),401);const uid=session.user.id,b=await request.json() as any;
if(b.action==='join'){if(typeof b.name!=='string'||!b.name.trim()||b.name.length>60)throw new Error('Choose a username.');if(b.avatar_url&& (typeof b.avatar_url!=='string'||!b.avatar_url.startsWith('https://')||b.avatar_url.length>2000))throw new Error('Use an HTTPS avatar image URL.');await userData(session,`profiles?id=eq.${uid}`,{method:'PATCH',body:{username:b.name.trim(),...(b.avatar_url!==undefined?{avatar_url:b.avatar_url||null}:{})}});}
else if(b.action==='createClub'){if(typeof b.name!=='string'||!b.name.trim()||b.name.length>100)throw new Error('Enter a club name.');await userData(session,'rpc/create_film_club',{method:'POST',body:{club_name:b.name.trim()}});}
else if(b.action==='joinClub'){if(typeof b.code!=='string'||!/^\w{8}-\w{4}-\w{4}-\w{4}-\w{12}$/.test(b.code))throw new Error('Enter a valid club code.');await userData(session,'rpc/join_film_club',{method:'POST',body:{code:b.code}});}
else if(b.action==='markRead'){if(typeof b.id!=='string'||!/^[-a-f0-9]{36}$/.test(b.id))throw new Error('Invalid recommendation.');await userData(session,`recommendations?id=eq.${b.id}&receiver_id=eq.${uid}`,{method:'PATCH',body:{is_read:true}});}
else{const m=b.movie;if(!m||!Number.isSafeInteger(m.id)||m.id<1||typeof m.title!=='string'||m.title.length>500||JSON.stringify(m).length>12000)throw new Error('Choose a valid movie.');
if(b.action==='review'){const value=reviewInput(b);await userData(session,'reviews?on_conflict=user_id,movie_id',{method:'POST',prefer:'resolution=merge-duplicates',body:{user_id:uid,movie_id:m.id,movie_title:m.title,poster_url:m.poster||null,movie:m,rating:value.rating||null,liked:Boolean(value.liked),review_text:value.body,screen_verdict:value.verdict,theatre_worthy:value.verdict==='theatre'?true:value.verdict==='home'?false:null}});}
else if(b.action==='save'){await userData(session,b.remove?`watchlist?user_id=eq.${uid}&movie_id=eq.${m.id}`:'watchlist?on_conflict=user_id,movie_id',{method:b.remove?'DELETE':'POST',prefer:'resolution=ignore-duplicates',body:b.remove?undefined:{user_id:uid,movie_id:m.id,movie:m}});}
else if(b.action==='recommend'){if(typeof b.recipient!=='string'||typeof b.club_id!=='string'||!/^[-a-f0-9]{36}$/.test(b.recipient)||!/^[-a-f0-9]{36}$/.test(b.club_id)||typeof b.body!=='string'||!b.body.trim()||b.body.length>3000)throw new Error('Choose a club, a recipient, and write a note.');await userData(session,'recommendations',{method:'POST',body:{club_id:b.club_id,sender_id:uid,receiver_id:b.recipient,movie_id:m.id,movie_title:m.title,poster_url:m.poster||null,movie:m,note:b.body.trim()}});}
else throw new Error('Unknown action.');}return Response.json({ok:true});}catch(error){return failure(error)}}
