import {reviewInput} from '@/lib/review';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database,failure} from '@/lib/server';
export async function GET(){try{const user=await getChatGPTUser(),db=database();const profile=user?await db.prepare('SELECT name FROM profiles WHERE id=?').bind(user.userId).first():null;const reviews=await db.prepare('SELECT r.*, p.name FROM reviews r JOIN profiles p ON p.id=r.user_id ORDER BY r.created DESC LIMIT 100').all();const myReviews=user?await db.prepare('SELECT r.*,p.name FROM reviews r JOIN profiles p ON p.id=r.user_id WHERE r.user_id=? ORDER BY r.created DESC').bind(user.userId).all():{results:[]};const people=await db.prepare('SELECT id,name FROM profiles ORDER BY name LIMIT 100').all();const saved=user?await db.prepare('SELECT movie FROM watchlist WHERE user_id=?').bind(user.userId).all():{results:[]};const messages=user?await db.prepare('SELECT m.*,p.name AS sender_name FROM messages m JOIN profiles p ON p.id=m.sender WHERE m.sender=? OR m.recipient=? ORDER BY m.created DESC LIMIT 200').bind(user.userId,user.userId).all():{results:[]};return Response.json({user:user?{id:user.userId,name:profile?.name||user.fullName||'Film lover'}:null,reviews:reviews.results,myReviews:myReviews.results,people:people.results,saved:saved.results.map((r:any)=>JSON.parse(r.movie)),messages:messages.results});}catch(e){return failure(e,503)}}
export async function POST(request:Request){try{if(request.headers.get('origin')!==new URL(request.url).origin)return failure(new Error('Invalid request origin.'),403);const user=await getChatGPTUser();if(!user)return failure(new Error('Sign in to save reviews and send recommendations.'),401);const b=await request.json() as any,db=database();const name=(typeof b.name==='string'?b.name:user.fullName||'Film lover').trim().slice(0,60)||'Film lover';await db.prepare(b.action==='join'?'INSERT INTO profiles(id,name) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name':'INSERT INTO profiles(id,name) VALUES(?,?) ON CONFLICT(id) DO NOTHING').bind(user.userId,name).run();if(b.action==='join')return Response.json({ok:true});if(b.action==='review'||b.action==='save'){if(!b.movie||!Number.isSafeInteger(b.movie.id)||typeof b.movie.title!=='string'||JSON.stringify(b.movie).length>12000)throw new Error('Choose a valid movie.');}
if(b.action==='review'){const value=reviewInput(b);const existing=await db.prepare('SELECT id FROM reviews WHERE user_id=? AND movie_id=? ORDER BY created DESC LIMIT 1').bind(user.userId,b.movie.id).first();if(existing){await db.prepare('UPDATE reviews SET body=?,rating=?,verdict=?,liked=?,movie=?,created=? WHERE id=? AND user_id=?').bind(value.body,value.rating,value.verdict,value.liked,JSON.stringify(b.movie),Date.now(),existing.id,user.userId).run();}else{await db.prepare('INSERT INTO reviews(id,user_id,movie_id,movie,body,rating,verdict,liked,created) VALUES(?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),user.userId,b.movie.id,JSON.stringify(b.movie),value.body,value.rating,value.verdict,value.liked,Date.now()).run();}}

else if(b.action==='save'){if(b.remove)await db.prepare('DELETE FROM watchlist WHERE user_id=? AND movie_id=?').bind(user.userId,b.movie.id).run();else await db.prepare('INSERT INTO watchlist(user_id,movie_id,movie) VALUES(?,?,?) ON CONFLICT(user_id,movie_id) DO NOTHING').bind(user.userId,b.movie.id,JSON.stringify(b.movie)).run();}
else if(b.action==='message'){if(typeof b.recipient!=='string'||typeof b.body!=='string'||!b.body.trim()||b.body.length>3000)throw new Error('Choose a person and write a message.');if(!await db.prepare('SELECT id FROM profiles WHERE id=?').bind(b.recipient).first())throw new Error('This member could not be found.');if(b.movie&&(!Number.isSafeInteger(b.movie.id)||typeof b.movie.title!=='string'||JSON.stringify(b.movie).length>12000))throw new Error('Invalid movie attachment.');await db.prepare('INSERT INTO messages(id,sender,recipient,body,movie,created) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),user.userId,b.recipient,b.body.trim(),b.movie?JSON.stringify(b.movie):null,Date.now()).run();}else throw new Error('Unknown action.');return Response.json({ok:true});}catch(e){return failure(e)}}
